Update templates to replace entire default URL with a token

diff --git a/java/11/alpine/3.13/detect/template/buildless/Dockerfile b/java/11/alpine/3.13/detect/template/buildless/Dockerfile
--- a/java/11/alpine/3.13/detect/template/buildless/Dockerfile
+++ b/java/11/alpine/3.13/detect/template/buildless/Dockerfile
@@ -10,9 +10,9 @@ ENV BDS_JAVA_HOME=/usr/lib/jvm/java-11-openjdk
 
 # Download Detect jar
 
-ARG DETECT_SOURCE=https://sig-repo.synopsys.com/bds-integrations-release/com/synopsys/integration/synopsys-detect/<detectVersion>/synopsys-detect-<detectVersion>.jar
+ARG DETECT_SOURCE=<detectsource>
 
-RUN if [ $(curl --silent -L -w '%{http_code}' -o /synopsys-detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect <detectVersion> jar" && exit 1; fi
+RUN if [ $(curl --silent -L -w '%{http_code}' -o /synopsys-detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect jar from ${DETECT_SOURCE}"; exit 1; fi
 
 # Define Docker Image entrypoint
 ENTRYPOINT ["java", "-jar", "/synopsys-detect.jar", "--detect.source.path=/source", "--detect.output.path=/output", "--detect.phone.home.passthrough.invoked.by.image=true", "--detect.detector.buildless=true"]
