Revert "Add set -e to exit script if command fails"
This reverts commit 24ddf8e0c51d236f901f0f30c94f56a23c246953.

diff --git a/java/11/ubuntu/22.10/detect/template/iac/Dockerfile b/java/11/ubuntu/22.10/detect/template/iac/Dockerfile
--- a/java/11/ubuntu/22.10/detect/template/iac/Dockerfile
+++ b/java/11/ubuntu/22.10/detect/template/iac/Dockerfile
@@ -20,7 +20,7 @@ ENV LC_ALL en_US.UTF-8
 
 ARG DETECT_SOURCE=<detectsource>
 
-RUN set -e; if [ $(curl --silent -L -w '%{http_code}' -o /synopsys-detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect jar from ${DETECT_SOURCE}"; exit 1; fi
+RUN if [ $(curl --silent -L -w '%{http_code}' -o /synopsys-detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect jar from ${DETECT_SOURCE}"; exit 1; fi
 
 # Define Docker Image entrypoint
 ENTRYPOINT ["java", "-jar", "/synopsys-detect.jar", "--detect.source.path=/source", "--detect.output.path=/output", "--detect.phone.home.passthrough.invoked.by.image=true"]
